/**
 * Shared learning utilities used across server and client components.
 *
 * Covers: category config, section-aware progress logic, and certificate
 * utilities.
 */

import {
  Shield,
  Lightbulb,
  Users,
  FileText,
  FileCode2,
  PlayCircle,
  Presentation,
  CheckCircle2,
  Lock,
  Circle,
} from "lucide-react";
import type { CourseCategory } from "@/types/database.types";
import type { BadgeProps } from "@/components/ui/badge";

// ─── Course Category Config ─────────────────────────────────────────────────

export interface CategoryConfig {
  label: string;
  icon: typeof Shield;
  color: string;
  bgColor: string;
  borderColor: string;
  badgeVariant: NonNullable<BadgeProps["variant"]>;
}

export const categoryConfig: Record<CourseCategory, CategoryConfig> = {
  compliance: {
    label: "Compliance",
    icon: Shield,
    color: "text-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-l-red-500",
    badgeVariant: "destructive",
  },
  upskilling: {
    label: "Upskilling",
    icon: Lightbulb,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-l-blue-500",
    badgeVariant: "default",
  },
  soft_skills: {
    label: "Soft Skills",
    icon: Users,
    color: "text-purple-600",
    bgColor: "bg-purple-50",
    borderColor: "border-l-purple-500",
    badgeVariant: "secondary",
  },
};

// Neutral fallback for a course_category not present in `categoryConfig` — e.g. a
// new enum value added in the DB before this map is updated. Keeps the UI from
// crashing on an undefended `categoryConfig[category]` lookup.
export const DEFAULT_CATEGORY_CONFIG: CategoryConfig = {
  label: "Other",
  icon: Circle,
  color: "text-muted-foreground",
  bgColor: "bg-muted",
  borderColor: "border-l-muted-foreground",
  badgeVariant: "secondary",
};

/**
 * Look up a course-category's display config, falling back to a neutral default
 * for any value not in `categoryConfig`. Guards against enum/config drift: the
 * type says every `CourseCategory` is a key, but the DB column can outrun this
 * map. Prefer this over a bare `categoryConfig[category]`.
 */
export function getCategoryConfig(category: CourseCategory): CategoryConfig {
  return categoryConfig[category] ?? DEFAULT_CATEGORY_CONFIG;
}

// ─── Lesson Type Config ─────────────────────────────────────────────────────

export type LessonType = "video" | "text" | "slides" | "rich_text";

export interface LessonTypeConfig {
  label: string;
  icon: typeof FileText;
}

export const lessonTypeConfig: Record<LessonType, LessonTypeConfig> = {
  video: { label: "Video", icon: PlayCircle },
  text: { label: "Text", icon: FileText },
  slides: { label: "Slides", icon: Presentation },
  rich_text: { label: "Rich Text", icon: FileCode2 },
};

// ─── Lesson Progress Icons ──────────────────────────────────────────────────

export const lessonProgressIcons = {
  completed: CheckCircle2,
  current: Circle,
  pending: Circle,
  locked: Lock,
} as const;

// ─── Section-Aware Locking Logic ────────────────────────────────────────────

export interface SectionInput {
  id: string;
  sort_order: number;
}

/**
 * Determines which sections are locked based on unpassed section quizzes.
 * A section is locked if ANY preceding section (by sort_order) has
 * an active quiz that the user hasn't passed.
 *
 * @param sections - All sections for a course, ordered by sort_order
 * @param passedQuizSectionIds - Set of section IDs where user has passed the quiz
 * @param sectionsWithQuizzes - Set of section IDs that HAVE an active quiz
 * @returns Set of locked section IDs
 */
export function getLockedSectionIds(
  sections: SectionInput[],
  passedQuizSectionIds: Set<string>,
  sectionsWithQuizzes: Set<string>
): Set<string> {
  const locked = new Set<string>();
  let blocking = false;

  for (const section of sections) {
    if (blocking) {
      locked.add(section.id);
    } else if (
      sectionsWithQuizzes.has(section.id) &&
      !passedQuizSectionIds.has(section.id)
    ) {
      // This section has an unpassed quiz — lock everything after it
      blocking = true;
    }
  }

  return locked;
}

/**
 * Calculate section-aware course progress.
 * Progress = (completed lessons + passed section quizzes) /
 *            (total active lessons + total active section quizzes)
 */
export function calculateSectionProgress(
  completedLessonCount: number,
  totalLessonCount: number,
  passedQuizCount: number,
  totalQuizCount: number
): number {
  const total = totalLessonCount + totalQuizCount;
  if (total === 0) return 0;
  const completed = completedLessonCount + passedQuizCount;
  return Math.round((completed / total) * 100);
}

// ─── Certificate Utilities ──────────────────────────────────────────────────

/**
 * Format a certificate number for display.
 * Numbers are generated by the DB function `generate_certificate_number()`.
 * Format: MCR-YYYY-XXXXX (e.g. MCR-2026-00001)
 */
export function formatCertificateNumber(number: string): string {
  return number;
}

// ─── Notification Type Config ───────────────────────────────────────────────

export const learningNotificationTypes = {
  course_assigned: {
    title: "Course Assigned",
    icon: "📚",
  },
  certificate_earned: {
    title: "Certificate Earned",
    icon: "🏆",
  },
  course_overdue_7d: {
    title: "Course Due Soon",
    icon: "⚠️",
  },
  course_overdue_1d: {
    title: "Course Due Tomorrow",
    icon: "🚨",
  },
} as const;

// ─── Duration Formatting ────────────────────────────────────────────────────

/**
 * Format duration in minutes to a human-readable string.
 * e.g. 45 → "45 min", 90 → "1h 30 min", 120 → "2h"
 */
export function formatDuration(minutes: number | null): string {
  if (!minutes) return "";
  if (minutes < 60) return `${minutes} min`;
  const hours = Math.floor(minutes / 60);
  const remaining = minutes % 60;
  if (remaining === 0) return `${hours}h`;
  return `${hours}h ${remaining} min`;
}

// ─── Legacy (deprecated) ────────────────────────────────────────────────────

/**
 * @deprecated Use getLockedSectionIds instead.
 * Kept for backward compatibility during migration.
 */
export function getLockedLessonIds(
  lessons: { id: string; lesson_type: string | null }[],
  completedLessonIds: string[]
): Set<string> {
  const locked = new Set<string>();
  let blockingQuizFound = false;

  for (const l of lessons) {
    if (blockingQuizFound) {
      locked.add(l.id);
    } else if (
      l.lesson_type === "quiz" &&
      !completedLessonIds.includes(l.id)
    ) {
      blockingQuizFound = true;
    }
  }

  return locked;
}

// ─── Preview mode ──────────────────────────────────────────────────

/**
 * Determines if the current request is in admin preview mode.
 * Returns isPreview: true only if ?preview=true AND user is an L&D admin.
 * searchParamString can be appended to all internal navigation links.
 */
export function getPreviewMode(
  searchParams: Record<string, string | string[] | undefined>,
  profile: { is_ld_admin?: boolean | null; status?: string } | null
): { isPreview: boolean; searchParamString: string } {
  const previewParam = searchParams?.preview;
  const isPreviewRequested = previewParam === "true";

  if (!isPreviewRequested || !profile) {
    return { isPreview: false, searchParamString: "" };
  }

  // Only L&D admins can preview
  if (profile.status !== "active" || !profile.is_ld_admin) {
    return { isPreview: false, searchParamString: "" };
  }

  return { isPreview: true, searchParamString: "?preview=true" };
}
